{
 "title": "Custom Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Websocket Requests per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(websocket_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Tokens per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(websocket_tokens_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenAI api status error per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(openai_api_status_error_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Three in a row exceptions per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(three_in_a_row_exceptions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad request errors per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(bad_request_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Regular exceptions per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(regular_exceptions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid message in iostream per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(invalid_message_in_iostream_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Random exceptions per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(random_exceptions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Requests per 70s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(ping_requests_total[70s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly analysis skipped users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(skipped_users_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly analysis conversations started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(weekly_analysis_team_conversations_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly analysis conversations succeeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(weekly_analysis_team_conversation_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly analysis exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(weekly_analysis_exceptions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}